export const lawyers = [
  {
    id: 1,
    nameFA: "محمد همائی‌فر",
    nameEN: "Mohammad Homaifar",
    titleFA: "وکیل پایه یک دادگستری",
    titleEN: "Licensed Bar Attorney",
    specialtyFA: "حقوق مدنی و خانواده",
    specialtyEN: "Civil & Family Law",
    experience: 20,
    cases: 850,
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop",
    bioFA: "وکیل پایه یک دادگستری با تخصص در حقوق مدنی و خانواده. عضو کانون وکلای دادگستری مرکز.",
    bioEN: "Licensed bar attorney specializing in civil and family law. Member of the Central Bar Association.",
  },
  {
    id: 2,
    nameFA: "محسن عاقل میر رضایی",
    nameEN: "Mohsen Aghel Mir Rezaei",
    titleFA: "وکیل پایه یک دادگستری",
    titleEN: "Licensed Bar Attorney",
    specialtyFA: "حقوق کیفری و تجاری",
    specialtyEN: "Criminal & Commercial Law",
    experience: 15,
    cases: 620,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    bioFA: "وکیل پایه یک دادگستری با تجربه در حقوق کیفری و امور تجاری.",
    bioEN: "Licensed bar attorney with experience in criminal and commercial law.",
  },
  {
    id: 3,
    nameFA: "عارف حسین شهاوندی",
    nameEN: "Aref Hossein Shahavandi",
    titleFA: "مشاور حقوقی",
    titleEN: "Legal Consultant",
    specialtyFA: "امور ملکی و ثبتی",
    specialtyEN: "Property & Registration Law",
    experience: 10,
    cases: 400,
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop",
    bioFA: "مشاور حقوقی با تخصص در امور ملکی، ثبتی و قراردادها.",
    bioEN: "Legal consultant specializing in property, registration and contract matters.",
  },
  {
    id: 4,
    nameFA: "عرفان شهاوندی",
    nameEN: "Erfan Shahavandi",
    titleFA: "مشاور حقوقی",
    titleEN: "Legal Consultant",
    specialtyFA: "حقوق خانواده",
    specialtyEN: "Family Law",
    experience: 8,
    cases: 300,
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop",
    bioFA: "مشاور حقوقی با تمرکز بر دعاوی خانوادگی و حقوق خانواده.",
    bioEN: "Legal consultant focused on family disputes and family law.",
  },
];

export const articles = [
  {
    id: 1,
    slug: "guide-to-filing-petition",
    titleFA: "راهنمای جامع تنظیم دادخواست در دادگاه‌های حقوقی",
    titleEN: "Comprehensive Guide to Filing a Petition in Civil Courts",
    excerptFA: "دادخواست مهم‌ترین سند در طرح دعوای حقوقی است. در این مقاله به بررسی مراحل تنظیم صحیح دادخواست می‌پردازیم.",
    excerptEN: "The petition is the most important document in civil litigation. This article examines the steps to properly draft a petition.",
    categoryFA: "حقوق مدنی",
    categoryEN: "Civil Law",
    author: "محمد همائی‌فر",
    authorEN: "Mohammad Homaifar",
    date: "2024-12-01",
    readTime: 8,
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=400&fit=crop",
  },
  {
    id: 2,
    slug: "legal-rights-in-criminal-cases",
    titleFA: "حقوق متهم در پرونده‌های کیفری چیست؟",
    titleEN: "What Are the Rights of the Accused in Criminal Cases?",
    excerptFA: "آشنایی با حقوق قانونی متهم در مراحل مختلف دادرسی کیفری از دستگیری تا اجرای حکم",
    excerptEN: "Understanding the legal rights of the accused in various stages of criminal proceedings from arrest to sentence execution.",
    categoryFA: "حقوق کیفری",
    categoryEN: "Criminal Law",
    author: "محسن عاقل میر رضایی",
    authorEN: "Mohsen Aghel Mir Rezaei",
    date: "2024-11-20",
    readTime: 12,
    image: "https://images.unsplash.com/photo-1479142506502-19b3a3b7ff33?w=800&h=400&fit=crop",
  },
  {
    id: 3,
    slug: "divorce-law-iran",
    titleFA: "قوانین طلاق در ایران: حقوق زن و مرد",
    titleEN: "Divorce Laws in Iran: Rights of Men and Women",
    excerptFA: "بررسی جامع قوانین طلاق، شرایط، مراحل و حقوق طرفین در جریان دعوای طلاق",
    excerptEN: "Comprehensive review of divorce laws, conditions, procedures and rights of parties during divorce proceedings.",
    categoryFA: "حقوق خانواده",
    categoryEN: "Family Law",
    author: "عارف حسین شهاوندی",
    authorEN: "Aref Hossein Shahavandi",
    date: "2024-11-10",
    readTime: 15,
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=400&fit=crop",
  },
];

export const faqs = [
  {
    questionFA: "هزینه مشاوره اولیه چقدر است؟",
    questionEN: "How much does an initial consultation cost?",
    answerFA: "اولین جلسه مشاوره کاملاً رایگان است. پس از بررسی پرونده، هزینه‌های وکالت با توجه به پیچیدگی پرونده تعیین می‌شود.",
    answerEN: "The first consultation session is completely free. After reviewing the case, attorney fees are determined based on case complexity.",
  },
  {
    questionFA: "چطور به متن قوانین دسترسی پیدا کنم؟",
    questionEN: "How can I access the text of laws?",
    answerFA: "از بخش «قوانین» در منو می‌توانید به ساختار درختی تمام قوانین دسترسی داشته باشید و هر ماده را با آرای مرتبط مشاهده کنید.",
    answerEN: "From the 'Laws' section in the menu, you can access the tree structure of all laws and view each article with related rulings.",
  },
  {
    questionFA: "آیا امکان مشاوره آنلاین وجود دارد؟",
    questionEN: "Is online consultation available?",
    answerFA: "بله، ما خدمات مشاوره آنلاین از طریق تماس ویدیویی و تلفنی ارائه می‌دهیم.",
    answerEN: "Yes, we offer online consultation services via video and phone calls.",
  },
  {
    questionFA: "در چه دعاوی تخصص دارید؟",
    questionEN: "What types of cases do you specialize in?",
    answerFA: "ما در دعاوی حقوقی، کیفری، تجاری، خانوادگی، ملکی و بین‌المللی تخصص داریم.",
    answerEN: "We specialize in civil, criminal, commercial, family, property and international cases.",
  },
];
